version: '3'
services:
  app:
    build:
      context: .
#    image: Wearing-Connect_app:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: bundle exec puma -C config/puma.rb
    tty: true
    stdin_open: true
    volumes:
      - .:/Wearing-Connect
      - public-data:/Wearing-Connect/public
      - tmp-data:/Wearing-Connect/tmp
      - log-data:/Wearing-Connect/log
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/Wearing-Connect/public
      - tmp-data:/Wearing-Connect/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data: